package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountRoleMap generated by hbm2java
 */
@Entity
@Table(name = "account_role_map")
public class AccountRoleMap implements java.io.Serializable {

	private Integer accRoleId;
	private Role role;
	private Account accountByCreatorAccRoleId;
	private Account accountByAccId;
	private Date accRoleGrantedDate;

	public AccountRoleMap() {
	}

	public AccountRoleMap(Role role, Account accountByCreatorAccRoleId,
			Account accountByAccId, Date accRoleGrantedDate) {
		this.role = role;
		this.accountByCreatorAccRoleId = accountByCreatorAccRoleId;
		this.accountByAccId = accountByAccId;
		this.accRoleGrantedDate = accRoleGrantedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACC_ROLE_ID", unique = true, nullable = false)
	public Integer getAccRoleId() {
		return this.accRoleId;
	}

	public void setAccRoleId(Integer accRoleId) {
		this.accRoleId = accRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATOR_ACC_ROLE_ID")
	public Account getAccountByCreatorAccRoleId() {
		return this.accountByCreatorAccRoleId;
	}

	public void setAccountByCreatorAccRoleId(Account accountByCreatorAccRoleId) {
		this.accountByCreatorAccRoleId = accountByCreatorAccRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACC_ID")
	public Account getAccountByAccId() {
		return this.accountByAccId;
	}

	public void setAccountByAccId(Account accountByAccId) {
		this.accountByAccId = accountByAccId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACC_ROLE_GRANTED_DATE", length = 19)
	public Date getAccRoleGrantedDate() {
		return this.accRoleGrantedDate;
	}

	public void setAccRoleGrantedDate(Date accRoleGrantedDate) {
		this.accRoleGrantedDate = accRoleGrantedDate;
	}

}
