package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Figurelink generated by hbm2java
 */
@Entity
@Table(name = "figurelink")
public class Figurelink implements java.io.Serializable {

	private Integer figureId;
	private String figureDesc;
	private String figurePath;
	private Set<Questionfigure> questionfigures = new HashSet<Questionfigure>(0);
	private Set<Questionitemfigure> questionitemfigures = new HashSet<Questionitemfigure>(
			0);

	public Figurelink() {
	}

	public Figurelink(String figurePath) {
		this.figurePath = figurePath;
	}

	public Figurelink(String figureDesc, String figurePath,
			Set<Questionfigure> questionfigures,
			Set<Questionitemfigure> questionitemfigures) {
		this.figureDesc = figureDesc;
		this.figurePath = figurePath;
		this.questionfigures = questionfigures;
		this.questionitemfigures = questionitemfigures;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FIGURE_ID", unique = true, nullable = false)
	public Integer getFigureId() {
		return this.figureId;
	}

	public void setFigureId(Integer figureId) {
		this.figureId = figureId;
	}

	@Column(name = "FIGURE_DESC", length = 65535)
	public String getFigureDesc() {
		return this.figureDesc;
	}

	public void setFigureDesc(String figureDesc) {
		this.figureDesc = figureDesc;
	}

	@Column(name = "FIGURE_PATH", nullable = false, length = 65535)
	public String getFigurePath() {
		return this.figurePath;
	}

	public void setFigurePath(String figurePath) {
		this.figurePath = figurePath;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "figurelink")
	public Set<Questionfigure> getQuestionfigures() {
		return this.questionfigures;
	}

	public void setQuestionfigures(Set<Questionfigure> questionfigures) {
		this.questionfigures = questionfigures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "figurelink")
	public Set<Questionitemfigure> getQuestionitemfigures() {
		return this.questionitemfigures;
	}

	public void setQuestionitemfigures(
			Set<Questionitemfigure> questionitemfigures) {
		this.questionitemfigures = questionitemfigures;
	}

}
