package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission")
public class Permission implements java.io.Serializable {

	private Integer permissionId;
	private String permissionName;
	private boolean permissionValue;
	private String permissionDesc;
	private Set<RolePermissionMap> rolePermissionMaps = new HashSet<RolePermissionMap>(
			0);

	public Permission() {
	}

	public Permission(String permissionName, boolean permissionValue) {
		this.permissionName = permissionName;
		this.permissionValue = permissionValue;
	}

	public Permission(String permissionName, boolean permissionValue,
			String permissionDesc, Set<RolePermissionMap> rolePermissionMaps) {
		this.permissionName = permissionName;
		this.permissionValue = permissionValue;
		this.permissionDesc = permissionDesc;
		this.rolePermissionMaps = rolePermissionMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PERMISSION_ID", unique = true, nullable = false)
	public Integer getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "PERMISSION_NAME", nullable = false)
	public String getPermissionName() {
		return this.permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	@Column(name = "PERMISSION_VALUE", nullable = false)
	public boolean isPermissionValue() {
		return this.permissionValue;
	}

	public void setPermissionValue(boolean permissionValue) {
		this.permissionValue = permissionValue;
	}

	@Column(name = "PERMISSION_DESC", length = 65535)
	public String getPermissionDesc() {
		return this.permissionDesc;
	}

	public void setPermissionDesc(String permissionDesc) {
		this.permissionDesc = permissionDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<RolePermissionMap> getRolePermissionMaps() {
		return this.rolePermissionMaps;
	}

	public void setRolePermissionMaps(Set<RolePermissionMap> rolePermissionMaps) {
		this.rolePermissionMaps = rolePermissionMaps;
	}

}
