package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Questionfigure generated by hbm2java
 */
@Entity
@Table(name = "questionfigure")
public class Questionfigure implements java.io.Serializable {

	private Integer questFigId;
	private Question question;
	private Figurelink figurelink;
	private String questFigDesc;

	public Questionfigure() {
	}

	public Questionfigure(Question question, Figurelink figurelink,
			String questFigDesc) {
		this.question = question;
		this.figurelink = figurelink;
		this.questFigDesc = questFigDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUEST_FIG_ID", unique = true, nullable = false)
	public Integer getQuestFigId() {
		return this.questFigId;
	}

	public void setQuestFigId(Integer questFigId) {
		this.questFigId = questFigId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIGURE_ID")
	public Figurelink getFigurelink() {
		return this.figurelink;
	}

	public void setFigurelink(Figurelink figurelink) {
		this.figurelink = figurelink;
	}

	@Column(name = "QUEST_FIG_DESC", length = 65535)
	public String getQuestFigDesc() {
		return this.questFigDesc;
	}

	public void setQuestFigDesc(String questFigDesc) {
		this.questFigDesc = questFigDesc;
	}

}
