package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Questioninfo generated by hbm2java
 */
@Entity
@Table(name = "questioninfo")
public class Questioninfo implements java.io.Serializable {

	private Integer questInfoId;
	private Question question;
	private String questInfoProp;
	private String questInfoValue;

	public Questioninfo() {
	}

	public Questioninfo(String questInfoProp, String questInfoValue) {
		this.questInfoProp = questInfoProp;
		this.questInfoValue = questInfoValue;
	}

	public Questioninfo(Question question, String questInfoProp,
			String questInfoValue) {
		this.question = question;
		this.questInfoProp = questInfoProp;
		this.questInfoValue = questInfoValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUEST_INFO_ID", unique = true, nullable = false)
	public Integer getQuestInfoId() {
		return this.questInfoId;
	}

	public void setQuestInfoId(Integer questInfoId) {
		this.questInfoId = questInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "QUEST_INFO_PROP", nullable = false, length = 50)
	public String getQuestInfoProp() {
		return this.questInfoProp;
	}

	public void setQuestInfoProp(String questInfoProp) {
		this.questInfoProp = questInfoProp;
	}

	@Column(name = "QUEST_INFO_VALUE", nullable = false, length = 200)
	public String getQuestInfoValue() {
		return this.questInfoValue;
	}

	public void setQuestInfoValue(String questInfoValue) {
		this.questInfoValue = questInfoValue;
	}

}
