package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Questionowner generated by hbm2java
 */
@Entity
@Table(name = "questionowner")
public class Questionowner implements java.io.Serializable {

	private Integer questOwnerId;
	private Question question;
	private Lecturer lecturer;

	public Questionowner() {
	}

	public Questionowner(Question question, Lecturer lecturer) {
		this.question = question;
		this.lecturer = lecturer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUEST_OWNER_ID", unique = true, nullable = false)
	public Integer getQuestOwnerId() {
		return this.questOwnerId;
	}

	public void setQuestOwnerId(Integer questOwnerId) {
		this.questOwnerId = questOwnerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LECTR_ID")
	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

}
