package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Questionitemfigure generated by hbm2java
 */
@Entity
@Table(name = "questionitemfigure")
public class Questionitemfigure implements java.io.Serializable {

	private Integer itemFigId;
	private Questionitem questionitem;
	private Figurelink figurelink;
	private String itemFigDesc;

	public Questionitemfigure() {
	}

	public Questionitemfigure(Questionitem questionitem, Figurelink figurelink,
			String itemFigDesc) {
		this.questionitem = questionitem;
		this.figurelink = figurelink;
		this.itemFigDesc = itemFigDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ITEM_FIG_ID", unique = true, nullable = false)
	public Integer getItemFigId() {
		return this.itemFigId;
	}

	public void setItemFigId(Integer itemFigId) {
		this.itemFigId = itemFigId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUEST_ITEM_ID")
	public Questionitem getQuestionitem() {
		return this.questionitem;
	}

	public void setQuestionitem(Questionitem questionitem) {
		this.questionitem = questionitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIGURE_ID")
	public Figurelink getFigurelink() {
		return this.figurelink;
	}

	public void setFigurelink(Figurelink figurelink) {
		this.figurelink = figurelink;
	}

	@Column(name = "ITEM_FIG_DESC", length = 65535)
	public String getItemFigDesc() {
		return this.itemFigDesc;
	}

	public void setItemFigDesc(String itemFigDesc) {
		this.itemFigDesc = itemFigDesc;
	}

}
