package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Squestionsolution generated by hbm2java
 */
@Entity
@Table(name = "squestionsolution")
public class Squestionsolution implements java.io.Serializable {

	private Integer squestSolId;
	private Tquestionitem tquestionitemByTquestNextItemId;
	private Tquestionitem tquestionitemByTquestPreviousItemId;
	private Studentsolution studentsolution;
	private Tquestionitem tquestionitemByTquestItemId;
	private Byte squestSolOrder;
	private String squestSolComment;

	public Squestionsolution() {
	}

	public Squestionsolution(Tquestionitem tquestionitemByTquestNextItemId,
			Tquestionitem tquestionitemByTquestPreviousItemId,
			Studentsolution studentsolution,
			Tquestionitem tquestionitemByTquestItemId, Byte squestSolOrder,
			String squestSolComment) {
		this.tquestionitemByTquestNextItemId = tquestionitemByTquestNextItemId;
		this.tquestionitemByTquestPreviousItemId = tquestionitemByTquestPreviousItemId;
		this.studentsolution = studentsolution;
		this.tquestionitemByTquestItemId = tquestionitemByTquestItemId;
		this.squestSolOrder = squestSolOrder;
		this.squestSolComment = squestSolComment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SQUEST_SOL_ID", unique = true, nullable = false)
	public Integer getSquestSolId() {
		return this.squestSolId;
	}

	public void setSquestSolId(Integer squestSolId) {
		this.squestSolId = squestSolId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUEST_NEXT_ITEM_ID")
	public Tquestionitem getTquestionitemByTquestNextItemId() {
		return this.tquestionitemByTquestNextItemId;
	}

	public void setTquestionitemByTquestNextItemId(
			Tquestionitem tquestionitemByTquestNextItemId) {
		this.tquestionitemByTquestNextItemId = tquestionitemByTquestNextItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUEST_PREVIOUS_ITEM_ID")
	public Tquestionitem getTquestionitemByTquestPreviousItemId() {
		return this.tquestionitemByTquestPreviousItemId;
	}

	public void setTquestionitemByTquestPreviousItemId(
			Tquestionitem tquestionitemByTquestPreviousItemId) {
		this.tquestionitemByTquestPreviousItemId = tquestionitemByTquestPreviousItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUDENT_SOL_ID")
	public Studentsolution getStudentsolution() {
		return this.studentsolution;
	}

	public void setStudentsolution(Studentsolution studentsolution) {
		this.studentsolution = studentsolution;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUEST_ITEM_ID")
	public Tquestionitem getTquestionitemByTquestItemId() {
		return this.tquestionitemByTquestItemId;
	}

	public void setTquestionitemByTquestItemId(
			Tquestionitem tquestionitemByTquestItemId) {
		this.tquestionitemByTquestItemId = tquestionitemByTquestItemId;
	}

	@Column(name = "SQUEST_SOL_ORDER")
	public Byte getSquestSolOrder() {
		return this.squestSolOrder;
	}

	public void setSquestSolOrder(Byte squestSolOrder) {
		this.squestSolOrder = squestSolOrder;
	}

	@Column(name = "SQUEST_SOL_COMMENT", length = 65535)
	public String getSquestSolComment() {
		return this.squestSolComment;
	}

	public void setSquestSolComment(String squestSolComment) {
		this.squestSolComment = squestSolComment;
	}

}
