package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Studentsolution generated by hbm2java
 */
@Entity
@Table(name = "studentsolution")
public class Studentsolution implements java.io.Serializable {

	private Integer studentSolId;
	private Student student;
	private Tquestion tquestion;
	private String studentSolComment;
	private Set<Squestionsolution> squestionsolutions = new HashSet<Squestionsolution>(
			0);

	public Studentsolution() {
	}

	public Studentsolution(Student student, Tquestion tquestion,
			String studentSolComment, Set<Squestionsolution> squestionsolutions) {
		this.student = student;
		this.tquestion = tquestion;
		this.studentSolComment = studentSolComment;
		this.squestionsolutions = squestionsolutions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STUDENT_SOL_ID", unique = true, nullable = false)
	public Integer getStudentSolId() {
		return this.studentSolId;
	}

	public void setStudentSolId(Integer studentSolId) {
		this.studentSolId = studentSolId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUDENT_ID")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUESTION_ID")
	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	@Column(name = "STUDENT_SOL_COMMENT", length = 65535)
	public String getStudentSolComment() {
		return this.studentSolComment;
	}

	public void setStudentSolComment(String studentSolComment) {
		this.studentSolComment = studentSolComment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentsolution")
	public Set<Squestionsolution> getSquestionsolutions() {
		return this.squestionsolutions;
	}

	public void setSquestionsolutions(Set<Squestionsolution> squestionsolutions) {
		this.squestionsolutions = squestionsolutions;
	}

}
