package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Subjectandtopic generated by hbm2java
 */
@Entity
@Table(name = "subjectandtopic")
public class Subjectandtopic implements java.io.Serializable {

	private Integer subjectTopId;
	private Topic topic;
	private Subject subject;
	private Float subjectTopPercent;

	public Subjectandtopic() {
	}

	public Subjectandtopic(Topic topic, Subject subject, Float subjectTopPercent) {
		this.topic = topic;
		this.subject = subject;
		this.subjectTopPercent = subjectTopPercent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SUBJECT_TOP_ID", unique = true, nullable = false)
	public Integer getSubjectTopId() {
		return this.subjectTopId;
	}

	public void setSubjectTopId(Integer subjectTopId) {
		this.subjectTopId = subjectTopId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TOPIC_ID")
	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBJECT_ID")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Column(name = "SUBJECT_TOP_PERCENT", precision = 12, scale = 0)
	public Float getSubjectTopPercent() {
		return this.subjectTopPercent;
	}

	public void setSubjectTopPercent(Float subjectTopPercent) {
		this.subjectTopPercent = subjectTopPercent;
	}

}
