package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subjectassignment generated by hbm2java
 */
@Entity
@Table(name = "subjectassignment")
public class Subjectassignment implements java.io.Serializable {

	private Integer assignId;
	private Lecturer lecturer;
	private Subject subject;
	private Date assignStartdate;
	private Date assignEnddate;

	public Subjectassignment() {
	}

	public Subjectassignment(Lecturer lecturer, Subject subject,
			Date assignStartdate, Date assignEnddate) {
		this.lecturer = lecturer;
		this.subject = subject;
		this.assignStartdate = assignStartdate;
		this.assignEnddate = assignEnddate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ASSIGN_ID", unique = true, nullable = false)
	public Integer getAssignId() {
		return this.assignId;
	}

	public void setAssignId(Integer assignId) {
		this.assignId = assignId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LECTR_ID")
	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBJECT_ID")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ASSIGN_STARTDATE", length = 10)
	public Date getAssignStartdate() {
		return this.assignStartdate;
	}

	public void setAssignStartdate(Date assignStartdate) {
		this.assignStartdate = assignStartdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ASSIGN_ENDDATE", length = 10)
	public Date getAssignEnddate() {
		return this.assignEnddate;
	}

	public void setAssignEnddate(Date assignEnddate) {
		this.assignEnddate = assignEnddate;
	}

}
