package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Testsectionitem generated by hbm2java
 */
@Entity
@Table(name = "testsectionitem")
public class Testsectionitem implements java.io.Serializable {

	private Integer testSecItemId;
	private Question question;
	private Testsection testsection;
	private Float testSecItemScore;

	public Testsectionitem() {
	}

	public Testsectionitem(Question question, Testsection testsection,
			Float testSecItemScore) {
		this.question = question;
		this.testsection = testsection;
		this.testSecItemScore = testSecItemScore;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TEST_SEC_ITEM_ID", unique = true, nullable = false)
	public Integer getTestSecItemId() {
		return this.testSecItemId;
	}

	public void setTestSecItemId(Integer testSecItemId) {
		this.testSecItemId = testSecItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUESTION_ID")
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEST_SEC_ID")
	public Testsection getTestsection() {
		return this.testsection;
	}

	public void setTestsection(Testsection testsection) {
		this.testsection = testsection;
	}

	@Column(name = "TEST_SEC_ITEM_SCORE", precision = 12, scale = 0)
	public Float getTestSecItemScore() {
		return this.testSecItemScore;
	}

	public void setTestSecItemScore(Float testSecItemScore) {
		this.testSecItemScore = testSecItemScore;
	}

}
