package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tfigurelink generated by hbm2java
 */
@Entity
@Table(name = "tfigurelink")
public class Tfigurelink implements java.io.Serializable {

	private Integer tfigureId;
	private String tfigureDesc;
	private String tfigurePath;
	private Set<Tquestionitemfigure> tquestionitemfigures = new HashSet<Tquestionitemfigure>(
			0);
	private Set<Tquestionfigure> tquestionfigures = new HashSet<Tquestionfigure>(
			0);

	public Tfigurelink() {
	}

	public Tfigurelink(String tfigureDesc, String tfigurePath,
			Set<Tquestionitemfigure> tquestionitemfigures,
			Set<Tquestionfigure> tquestionfigures) {
		this.tfigureDesc = tfigureDesc;
		this.tfigurePath = tfigurePath;
		this.tquestionitemfigures = tquestionitemfigures;
		this.tquestionfigures = tquestionfigures;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TFIGURE_ID", unique = true, nullable = false)
	public Integer getTfigureId() {
		return this.tfigureId;
	}

	public void setTfigureId(Integer tfigureId) {
		this.tfigureId = tfigureId;
	}

	@Column(name = "TFIGURE_DESC", length = 65535)
	public String getTfigureDesc() {
		return this.tfigureDesc;
	}

	public void setTfigureDesc(String tfigureDesc) {
		this.tfigureDesc = tfigureDesc;
	}

	@Column(name = "TFIGURE_PATH", length = 65535)
	public String getTfigurePath() {
		return this.tfigurePath;
	}

	public void setTfigurePath(String tfigurePath) {
		this.tfigurePath = tfigurePath;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfigurelink")
	public Set<Tquestionitemfigure> getTquestionitemfigures() {
		return this.tquestionitemfigures;
	}

	public void setTquestionitemfigures(
			Set<Tquestionitemfigure> tquestionitemfigures) {
		this.tquestionitemfigures = tquestionitemfigures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfigurelink")
	public Set<Tquestionfigure> getTquestionfigures() {
		return this.tquestionfigures;
	}

	public void setTquestionfigures(Set<Tquestionfigure> tquestionfigures) {
		this.tquestionfigures = tquestionfigures;
	}

}
