package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Topic generated by hbm2java
 */
@Entity
@Table(name = "topic")
public class Topic implements java.io.Serializable {

	private String topicId;
	private Topic topic;
	private String topicName;
	private String topicDesc;
	private Set<Topic> topics = new HashSet<Topic>(0);
	private Set<Tquestiontopic> tquestiontopics = new HashSet<Tquestiontopic>(0);
	private Set<Subjectandtopic> subjectandtopics = new HashSet<Subjectandtopic>(
			0);
	private Set<Questiontopic> questiontopics = new HashSet<Questiontopic>(0);

	public Topic() {
	}

	public Topic(String topicId, String topicName) {
		this.topicId = topicId;
		this.topicName = topicName;
	}

	public Topic(String topicId, Topic topic, String topicName,
			String topicDesc, Set<Topic> topics,
			Set<Tquestiontopic> tquestiontopics,
			Set<Subjectandtopic> subjectandtopics,
			Set<Questiontopic> questiontopics) {
		this.topicId = topicId;
		this.topic = topic;
		this.topicName = topicName;
		this.topicDesc = topicDesc;
		this.topics = topics;
		this.tquestiontopics = tquestiontopics;
		this.subjectandtopics = subjectandtopics;
		this.questiontopics = questiontopics;
	}

	@Id
	@Column(name = "TOPIC_ID", unique = true, nullable = false, length = 20)
	public String getTopicId() {
		return this.topicId;
	}

	public void setTopicId(String topicId) {
		this.topicId = topicId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TOPIC_PARENT_ID")
	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	@Column(name = "TOPIC_NAME", nullable = false, length = 200)
	public String getTopicName() {
		return this.topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	@Column(name = "TOPIC_DESC", length = 65535)
	public String getTopicDesc() {
		return this.topicDesc;
	}

	public void setTopicDesc(String topicDesc) {
		this.topicDesc = topicDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic")
	public Set<Topic> getTopics() {
		return this.topics;
	}

	public void setTopics(Set<Topic> topics) {
		this.topics = topics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic")
	public Set<Tquestiontopic> getTquestiontopics() {
		return this.tquestiontopics;
	}

	public void setTquestiontopics(Set<Tquestiontopic> tquestiontopics) {
		this.tquestiontopics = tquestiontopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic")
	public Set<Subjectandtopic> getSubjectandtopics() {
		return this.subjectandtopics;
	}

	public void setSubjectandtopics(Set<Subjectandtopic> subjectandtopics) {
		this.subjectandtopics = subjectandtopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic")
	public Set<Questiontopic> getQuestiontopics() {
		return this.questiontopics;
	}

	public void setQuestiontopics(Set<Questiontopic> questiontopics) {
		this.questiontopics = questiontopics;
	}

}
