package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tquestionitem generated by hbm2java
 */
@Entity
@Table(name = "tquestionitem")
public class Tquestionitem implements java.io.Serializable {

	private Integer tquestItemId;
	private Tquestion tquestion;
	private String tquestItemFace;
	private String tquestItemValue;
	private Set<Squestionsolution> squestionsolutionsForTquestNextItemId = new HashSet<Squestionsolution>(
			0);
	private Set<Tquestionsolution> tquestionsolutionsForTquestPreviousItemId = new HashSet<Tquestionsolution>(
			0);
	private Set<Tquestioniteminfo> tquestioniteminfos = new HashSet<Tquestioniteminfo>(
			0);
	private Set<Squestionsolution> squestionsolutionsForTquestPreviousItemId = new HashSet<Squestionsolution>(
			0);
	private Set<Squestionsolution> squestionsolutionsForTquestItemId = new HashSet<Squestionsolution>(
			0);
	private Set<Tquestionsolution> tquestionsolutionsForTquestItemId = new HashSet<Tquestionsolution>(
			0);
	private Set<Tquestionitemfigure> tquestionitemfigures = new HashSet<Tquestionitemfigure>(
			0);
	private Set<Tquestionsolution> tquestionsolutionsForTquestNextItemId = new HashSet<Tquestionsolution>(
			0);

	public Tquestionitem() {
	}

	public Tquestionitem(Tquestion tquestion, String tquestItemFace,
			String tquestItemValue,
			Set<Squestionsolution> squestionsolutionsForTquestNextItemId,
			Set<Tquestionsolution> tquestionsolutionsForTquestPreviousItemId,
			Set<Tquestioniteminfo> tquestioniteminfos,
			Set<Squestionsolution> squestionsolutionsForTquestPreviousItemId,
			Set<Squestionsolution> squestionsolutionsForTquestItemId,
			Set<Tquestionsolution> tquestionsolutionsForTquestItemId,
			Set<Tquestionitemfigure> tquestionitemfigures,
			Set<Tquestionsolution> tquestionsolutionsForTquestNextItemId) {
		this.tquestion = tquestion;
		this.tquestItemFace = tquestItemFace;
		this.tquestItemValue = tquestItemValue;
		this.squestionsolutionsForTquestNextItemId = squestionsolutionsForTquestNextItemId;
		this.tquestionsolutionsForTquestPreviousItemId = tquestionsolutionsForTquestPreviousItemId;
		this.tquestioniteminfos = tquestioniteminfos;
		this.squestionsolutionsForTquestPreviousItemId = squestionsolutionsForTquestPreviousItemId;
		this.squestionsolutionsForTquestItemId = squestionsolutionsForTquestItemId;
		this.tquestionsolutionsForTquestItemId = tquestionsolutionsForTquestItemId;
		this.tquestionitemfigures = tquestionitemfigures;
		this.tquestionsolutionsForTquestNextItemId = tquestionsolutionsForTquestNextItemId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TQUEST_ITEM_ID", unique = true, nullable = false)
	public Integer getTquestItemId() {
		return this.tquestItemId;
	}

	public void setTquestItemId(Integer tquestItemId) {
		this.tquestItemId = tquestItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUESTION_ID")
	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	@Column(name = "TQUEST_ITEM_FACE", length = 65535)
	public String getTquestItemFace() {
		return this.tquestItemFace;
	}

	public void setTquestItemFace(String tquestItemFace) {
		this.tquestItemFace = tquestItemFace;
	}

	@Column(name = "TQUEST_ITEM_VALUE", length = 65535)
	public String getTquestItemValue() {
		return this.tquestItemValue;
	}

	public void setTquestItemValue(String tquestItemValue) {
		this.tquestItemValue = tquestItemValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tquestionitemByTquestNextItemId")
	public Set<Squestionsolution> getSquestionsolutionsForTquestNextItemId() {
		return this.squestionsolutionsForTquestNextItemId;
	}

	public void setSquestionsolutionsForTquestNextItemId(
			Set<Squestionsolution> squestionsolutionsForTquestNextItemId) {
		this.squestionsolutionsForTquestNextItemId = squestionsolutionsForTquestNextItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tquestionitemByTquestPreviousItemId")
	public Set<Tquestionsolution> getTquestionsolutionsForTquestPreviousItemId() {
		return this.tquestionsolutionsForTquestPreviousItemId;
	}

	public void setTquestionsolutionsForTquestPreviousItemId(
			Set<Tquestionsolution> tquestionsolutionsForTquestPreviousItemId) {
		this.tquestionsolutionsForTquestPreviousItemId = tquestionsolutionsForTquestPreviousItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tquestionitem")
	public Set<Tquestioniteminfo> getTquestioniteminfos() {
		return this.tquestioniteminfos;
	}

	public void setTquestioniteminfos(Set<Tquestioniteminfo> tquestioniteminfos) {
		this.tquestioniteminfos = tquestioniteminfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tquestionitemByTquestPreviousItemId")
	public Set<Squestionsolution> getSquestionsolutionsForTquestPreviousItemId() {
		return this.squestionsolutionsForTquestPreviousItemId;
	}

	public void setSquestionsolutionsForTquestPreviousItemId(
			Set<Squestionsolution> squestionsolutionsForTquestPreviousItemId) {
		this.squestionsolutionsForTquestPreviousItemId = squestionsolutionsForTquestPreviousItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tquestionitemByTquestItemId")
	public Set<Squestionsolution> getSquestionsolutionsForTquestItemId() {
		return this.squestionsolutionsForTquestItemId;
	}

	public void setSquestionsolutionsForTquestItemId(
			Set<Squestionsolution> squestionsolutionsForTquestItemId) {
		this.squestionsolutionsForTquestItemId = squestionsolutionsForTquestItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tquestionitemByTquestItemId")
	public Set<Tquestionsolution> getTquestionsolutionsForTquestItemId() {
		return this.tquestionsolutionsForTquestItemId;
	}

	public void setTquestionsolutionsForTquestItemId(
			Set<Tquestionsolution> tquestionsolutionsForTquestItemId) {
		this.tquestionsolutionsForTquestItemId = tquestionsolutionsForTquestItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tquestionitem")
	public Set<Tquestionitemfigure> getTquestionitemfigures() {
		return this.tquestionitemfigures;
	}

	public void setTquestionitemfigures(
			Set<Tquestionitemfigure> tquestionitemfigures) {
		this.tquestionitemfigures = tquestionitemfigures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tquestionitemByTquestNextItemId")
	public Set<Tquestionsolution> getTquestionsolutionsForTquestNextItemId() {
		return this.tquestionsolutionsForTquestNextItemId;
	}

	public void setTquestionsolutionsForTquestNextItemId(
			Set<Tquestionsolution> tquestionsolutionsForTquestNextItemId) {
		this.tquestionsolutionsForTquestNextItemId = tquestionsolutionsForTquestNextItemId;
	}

}
