package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tquestioninfo generated by hbm2java
 */
@Entity
@Table(name = "tquestioninfo")
public class Tquestioninfo implements java.io.Serializable {

	private Integer tquestInfoId;
	private Tquestion tquestion;
	private String tquestInfoProp;
	private String tquestInfoValue;

	public Tquestioninfo() {
	}

	public Tquestioninfo(String tquestInfoProp) {
		this.tquestInfoProp = tquestInfoProp;
	}

	public Tquestioninfo(Tquestion tquestion, String tquestInfoProp,
			String tquestInfoValue) {
		this.tquestion = tquestion;
		this.tquestInfoProp = tquestInfoProp;
		this.tquestInfoValue = tquestInfoValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TQUEST_INFO_ID", unique = true, nullable = false)
	public Integer getTquestInfoId() {
		return this.tquestInfoId;
	}

	public void setTquestInfoId(Integer tquestInfoId) {
		this.tquestInfoId = tquestInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUESTION_ID")
	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	@Column(name = "TQUEST_INFO_PROP", nullable = false, length = 50)
	public String getTquestInfoProp() {
		return this.tquestInfoProp;
	}

	public void setTquestInfoProp(String tquestInfoProp) {
		this.tquestInfoProp = tquestInfoProp;
	}

	@Column(name = "TQUEST_INFO_VALUE", length = 200)
	public String getTquestInfoValue() {
		return this.tquestInfoValue;
	}

	public void setTquestInfoValue(String tquestInfoValue) {
		this.tquestInfoValue = tquestInfoValue;
	}

}
