package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tquestionowner generated by hbm2java
 */
@Entity
@Table(name = "tquestionowner")
public class Tquestionowner implements java.io.Serializable {

	private Integer tquestOwnerId;
	private Tquestion tquestion;
	private Lecturer lecturer;

	public Tquestionowner() {
	}

	public Tquestionowner(Tquestion tquestion, Lecturer lecturer) {
		this.tquestion = tquestion;
		this.lecturer = lecturer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TQUEST_OWNER_ID", unique = true, nullable = false)
	public Integer getTquestOwnerId() {
		return this.tquestOwnerId;
	}

	public void setTquestOwnerId(Integer tquestOwnerId) {
		this.tquestOwnerId = tquestOwnerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUESTION_ID")
	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LECTR_ID")
	public Lecturer getLecturer() {
		return this.lecturer;
	}

	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}

}
