package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tquestiontopic generated by hbm2java
 */
@Entity
@Table(name = "tquestiontopic")
public class Tquestiontopic implements java.io.Serializable {

	private Integer tquestTopicId;
	private Topic topic;
	private Tquestion tquestion;
	private Character tquestTopicLevel;

	public Tquestiontopic() {
	}

	public Tquestiontopic(Topic topic, Tquestion tquestion,
			Character tquestTopicLevel) {
		this.topic = topic;
		this.tquestion = tquestion;
		this.tquestTopicLevel = tquestTopicLevel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TQUEST_TOPIC_ID", unique = true, nullable = false)
	public Integer getTquestTopicId() {
		return this.tquestTopicId;
	}

	public void setTquestTopicId(Integer tquestTopicId) {
		this.tquestTopicId = tquestTopicId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TOPIC_ID")
	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUESTION_ID")
	public Tquestion getTquestion() {
		return this.tquestion;
	}

	public void setTquestion(Tquestion tquestion) {
		this.tquestion = tquestion;
	}

	@Column(name = "TQUEST_TOPIC_LEVEL", length = 1)
	public Character getTquestTopicLevel() {
		return this.tquestTopicLevel;
	}

	public void setTquestTopicLevel(Character tquestTopicLevel) {
		this.tquestTopicLevel = tquestTopicLevel;
	}

}
