package model;

// default package
// Generated Mar 15, 2014 7:27:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tquestionitemfigure generated by hbm2java
 */
@Entity
@Table(name = "tquestionitemfigure")
public class Tquestionitemfigure implements java.io.Serializable {

	private Integer tquestItemFigId;
	private Tquestionitem tquestionitem;
	private Tfigurelink tfigurelink;
	private String tquestItemFigDesc;

	public Tquestionitemfigure() {
	}

	public Tquestionitemfigure(Tquestionitem tquestionitem,
			Tfigurelink tfigurelink, String tquestItemFigDesc) {
		this.tquestionitem = tquestionitem;
		this.tfigurelink = tfigurelink;
		this.tquestItemFigDesc = tquestItemFigDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TQUEST_ITEM_FIG_ID", unique = true, nullable = false)
	public Integer getTquestItemFigId() {
		return this.tquestItemFigId;
	}

	public void setTquestItemFigId(Integer tquestItemFigId) {
		this.tquestItemFigId = tquestItemFigId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TQUEST_ITEM_ID")
	public Tquestionitem getTquestionitem() {
		return this.tquestionitem;
	}

	public void setTquestionitem(Tquestionitem tquestionitem) {
		this.tquestionitem = tquestionitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TFIGURE_ID")
	public Tfigurelink getTfigurelink() {
		return this.tfigurelink;
	}

	public void setTfigurelink(Tfigurelink tfigurelink) {
		this.tfigurelink = tfigurelink;
	}

	@Column(name = "TQUEST_ITEM_FIG_DESC", length = 65535)
	public String getTquestItemFigDesc() {
		return this.tquestItemFigDesc;
	}

	public void setTquestItemFigDesc(String tquestItemFigDesc) {
		this.tquestItemFigDesc = tquestItemFigDesc;
	}

}
